sudo : required
services :
  - docker

before_install :
  - docker build -t entityvsentityv2/react-test -f ./client/Dockerfile.dev ./client

script :
  - docker run entityvsentityv2/react-test npm test -- --coverage --watchAll=false

after_success :
  - docker build -t entityvsentityv2/multi-client ./client
  - docker build -t entityvsentityv2/multi-nginx ./nginx
  - docker build -t entityvsentityv2/multi-server ./server
  - docker build -t entityvsentityv2/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push entityvsentityv2/multi-client
  - docker push entityvsentityv2/multi-nginx
  - docker push entityvsentityv2/multi-server
  - docker push entityvsentityv2/multi-worker

deploy :
  provider : elasticbeanstalk
  region : "us-east-1" 
  app : "multi-docker"
  env : "MultiDocker-env"
  bucket_name : "elasticbeanstalk-us-east-1-244805251636"
  bucket_path : "docker-multi"
  on:
    branch : master
  access_key_id : $AWS_ACCESS_KEY
  secret_access_key :
    secure : "$AWS_SECRET_KEY"  